name: Checkout de código

on:
  push:

jobs:

  checkout_code:
    name: Faz checkout do codigo
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repositório
      uses: actions/checkout@v3.3.0

    - name: Lista conteúdo do runner
      run: ls -a
